# Numpy

## 1: Take a 3x3 matrix randomly and another matrix by assigning elements. Now add the 2 matrix and store it in a seperate matrix C

In [1]:
import numpy as np
a=np.random.randint(0,10,9).reshape(3,3)
print(a)
b=[[1,2,3],[4,5,6],[7,8,9]]
c=np.add(a,b)
print(c)

[[2 6 1]
 [1 0 8]
 [0 3 8]]
[[ 3  8  4]
 [ 5  5 14]
 [ 7 11 17]]


## 2: Take 3X3 matrixes add it with another 3x3 of all 1 matrix and convert that to a complex data type matrix.

In [2]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.ones(9).reshape(3,3)
c=np.add(a,b,dtype=complex)
print(c)

[[ 2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j]]


## 3: Take a 3X3 matrix and multiply element wise with 3X 3 another matrix.

In [3]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,2,3],[4,5,6],[7,8,9]]
c=np.multiply(a,b)
print(c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## 4: Multiply 2 3X3 matrixes.

In [4]:
import numpy as np
a=np.random.randint(0,10,9).reshape(3,3)
print(a)
b=np.random.randint(0,10,9).reshape(3,3)
print(b)
c=np.zeros(9,dtype='int').reshape(3,3)
for i in range(3):
    for j in range(3):
        sum=0
        for k in range(3):
            sum=sum+a[i,k]*b[k,j]
        c[i,j]=sum
print(c)

[[3 2 8]
 [0 9 2]
 [0 0 3]]
[[9 7 2]
 [0 7 7]
 [6 5 7]]
[[75 75 76]
 [12 73 77]
 [18 15 21]]


## 5: Randomly generate 10 numbers in between 1 to 10 and convert that to a 5X2 matrix. Take a floating-point matrix and perform the addition. a= floating point matrix and b is an integer matrix of same dimension. Why a+=b is not equal to b+=a. Explain briefly. How can we resolve this problem?

In [5]:
import numpy as np
a=np.random.randint(1,10,10,dtype='int').reshape(5,2)
print(a)
b=np.random.uniform(1,10,10).reshape(5,2)
print(b)
a=a+b
print(a)

[[6 2]
 [1 9]
 [8 2]
 [4 8]
 [5 8]]
[[3.61965338 9.50695372]
 [9.91779789 5.32555223]
 [4.14415864 2.07394711]
 [5.99570755 1.2330204 ]
 [7.50260628 9.54356408]]
[[ 9.61965338 11.50695372]
 [10.91779789 14.32555223]
 [12.14415864  4.07394711]
 [ 9.99570755  9.2330204 ]
 [12.50260628 17.54356408]]


## 6: Take a multidimensional array (3, 3, 3) and print the last column.

In [6]:
import numpy as np
a=np.random.randint(0,10,27).reshape(3,3,3)
print(a)
b=a[:,:,2:]
print(b)

[[[4 7 1]
  [5 2 3]
  [8 0 5]]

 [[7 1 8]
  [5 9 8]
  [6 3 1]]

 [[0 7 6]
  [0 7 3]
  [0 3 1]]]
[[[1]
  [3]
  [5]]

 [[8]
  [8]
  [1]]

 [[6]
  [3]
  [1]]]


## 7: Take a function f(x) =x^3 + 5*y +4*z and determine the values and store them in a (3,3,3) matrix.

In [7]:
import numpy as np
def c(x,y,z):
    return x**3+5*y+4*z
b=np.fromfunction(c,(3,3,3),dtype=int)
print(b)

[[[ 0  4  8]
  [ 5  9 13]
  [10 14 18]]

 [[ 1  5  9]
  [ 6 10 14]
  [11 15 19]]

 [[ 8 12 16]
  [13 17 21]
  [18 22 26]]]


## 8: Using axis add the column values of a 3X3 matrix and then add it with the maximum values of rows taken in a  3x3 matrix.

In [8]:
import numpy as np
def c(x,y,z):
    return x**3+5*y+4*z
b=np.fromfunction(c,(3,3,3),dtype=int)
print(b)

[[[ 0  4  8]
  [ 5  9 13]
  [10 14 18]]

 [[ 1  5  9]
  [ 6 10 14]
  [11 15 19]]

 [[ 8 12 16]
  [13 17 21]
  [18 22 26]]]


## 9: f(x) = x^3 + 5y and store it in (3,3) matrix.

In [9]:
import numpy as np
def c(x,y):
    return x**3+5*y
b=np.fromfunction(c,(3,3),dtype=int)
print(b)

[[ 0  5 10]
 [ 1  6 11]
 [ 8 13 18]]


## 10: Take a function array 'a' cube with a range of 20 and find out what will be the value of a [[7,8], [9,11]]. If we take values a [[7, 8], [9, 21]] will it take if not why?

In [10]:
import numpy as np
def cube(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            arr[i][j]=arr[i][j]**3
    return arr
arr=[[5,6],[9,4]]
print(cube(arr))

[[125, 216], [729, 64]]


## 11: Take a random number from 0 to 19 and make a 4X5 matrix then find the values of (i) 3rd row and 4th column only and (ii) only 4th column values.

In [11]:
import numpy as np
a=np.arange(20).reshape(4,5)
print(a)
print(a[2,3])
print(a[:,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
13
[ 3  8 13 18]


## 12: Take a matrix of 5X4 randomly and create 2 3x3 values i and j respectively and take a tuple named m with i and j as an argument and generate the values of the matrix for the specified tuple. i<=4 and j<=3.

In [12]:
import numpy as np
a=np.arange(20).reshape(5,4)
print(a)
i=np.array([[0,1,2],[1,2,3],[2,3,4]])
j=np.array([[2,1,0],[3,1,2],[1,1,1]])
m=(i,j)
print("Generated values by specific tuple")
print(a[m])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Generated values by specific tuple
[[ 2  5  8]
 [ 7  9 14]
 [ 9 13 17]]


## 13: Take a matrix of 3x3 and find out the Eigen vector and Eigen values of that matrix. 14. Take a matrix and by taking the i, j or x, y values implement the hstack and vstack methods.

In [13]:
import numpy as np
a=np.arange(9).reshape(3,3)
print(np.linalg.eig(a))

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


## 14: Take a matrix and by taking the i,j or x,y values implement the hstack and vstack methods.

In [14]:
x=np.arange(0,10,2)
x
y=np.arange(1,10,2)
y
xy=np.vstack([x,y])
print(xy)
xoy=np.hstack([x,y])
print(xoy)

[[0 2 4 6 8]
 [1 3 5 7 9]]
[0 2 4 6 8 1 3 5 7 9]
